### ISSUE TITLE
Metadata Schema Compatibility

### ISSUE THREAD

**Issue by koolamusic** [0xilance/nfhack-0ne-14-16#3]
See ERC-721 Metadata JSON Schema standard.
See https://nftschool.dev/reference/metadata-schemas/#ethereum-and-evm-compatible-chains

```
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents"
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
        }
    }
}

```

We have to try and align with the Open Badge Schema
https://openbadges.org/

**Comment by 0xilance** [comment]
Take a look at this https://github.com/IMSGlobal/cert-schema/blob/master/docs/open_badge_v2_extensions.md#blockcerts-proposed-extensions-to-open-badges-v2 also has a reference for MerkleRoots

Here is a dump of the schema I extracted





{

  "data": {
      "id": 18845238,
      "group_id": 202258,
      "language": "en",
      "approve": true,
      "private_key": null,
      "private": false,
      "grade": null,
      "issued_on": "2020-05-31",
      "published_on": "2020-05-31",
      "expired_on": null,
      "encoded_id": "0utzo9hv",
      "license_id": 18845238,
      "employment_dir_notified": false,
      "uuid": "2538cd21-9155-4eae-a04b-0b1a55ff9ee1",
      "name": "Design Thinking Masterclass",
      "description": "Masterclass in Design Thinking",
      "complete": true,
      "learning_outcomes": [ ],
      "achievement_id": "202258",
      "allow_supplemental_references": null,
      "allow_supplemental_evidence": null,
      "course_link": "http://learn.ibm.com?aad=BAhJIj57InR5cGUiOiJjb3Vyc2UiLCJ1cmwiOiJodHRwOi8vdGVjbWllLmNvbSIsImlkIjoxODg0NTIzOH0GOgZFVA%3D%3D--a4527eb8ef19e258c8e90552e47ad8077baba9b8",
      "custom_attributes": { },
      "url": "https://www.credential.net/2538cd21-9155-4eae-a04b-0b1a55ff9ee1",
      "sample": false,
      "has_user": true,
      "verified_user": false,
      "expired": false,
      "email_embed_image": "https://api.null.com/v1/frontend/credential_email_embed_image/18845238",
      "opengraph_image": "https://api.null.com/v1/frontend/credential_opengraph_seo_image/18845238",
      "badge_assertion_url": null,
      "embed_image": "https://api.null.com/v1/frontend/credential_embed_image/18845238",
      "own_credential": false,
      "badge_image": null,
      "custom": { },
      "custom_type": { },
      "block_credential": true,
      "block_credential_address": "674212",
      "verified": false,
      "is_confirmed": false,
      "is_pending_confirmation": false,
      "website_email_embed_badge_image": null,
      "job_insights": { },
      "website_email_embed_certificate_image": "https://api.null.com/v1/frontend/credential_website_embed_image/certificate/18845238",
      "username": "andrewmiracle",
      "twittercard_image": "https://api.null.com/v1/frontend/credential_twittercard_seo_image/18845238",
      "user": {
          "profile": "https://www.openbadge.net/profile/vik"
      },
      "recipient": {
          "email": "**@a************.com",
          "name": "Andrew Miranda",
          "id": 8968861
      },
      "updated_at": "2020-05-31T22:48:18.019Z",
      "evidence_items": [ ],
      "references": [ ],
      "issuer": {
          "id": 45327,
          "name": "Google",
          "url": "http://learn.google.com?aad=BAhJIj57InR5cGUiOiJpc3N1ZXIiLCJ1cmwiOiJodHRwOi8vdGVjbWllLmNvbSIsImlkIjoxODg0NTIzOH0GOgZFVA%3D%3D--cf936f436153baf62d2681962bc8e1ffc9be0f28",
          "description": null,
          "image_url": null,
          "allow_supplemental_references": true,
          "allow_supplemental_evidence": true,
          "created_at": 1590957921,
          "language": "en",
          "customer": true,
          "whitelisted_domain": null,
          "twitter_handle": null,
          "certificate_expiry_message": null,
          "social_media": null,
          "recipient_functions": null,
          "name_changes_auto_approve": "typo",
          "support_contact_email": "andrew@tecmie.com",
          "logo": null,
          "employment_directory_domain": null,
          "employment_directory_published": false,
          "digital_wallet_passes": false
      },
      "group": {
          "id": 202258,
          "name": "Design Thinking",
          "language": "en",
          "course_description": "Masterclass in Design Thinking",
          "learning_outcomes": null,
          "course_link": "http://learn.google.com?aad=BAhJIj57InR5cGUiOiJjb3Vyc2UiLCJ1cmwiOiJodHRwOi8vdGVjbWllLmNvbSIsImlkIjoxODg0NTIzOH0GOgZFVA%3D%3D--a4527eb8ef19e258c8e90552e47ad8077baba9b8",
          "course_link_show": false,
          "signup_url": null,
          "signup_url_show": false,
          "organization_link_show": true,
          "course_name": "Design Thinking Masterclass",
          "expired_on": null,
          "attach_pdf": false,
          "is_linkedin_education_section": false,
          "expire": false,
          "issuer_name": null,
          "issuer_url": null,
          "transcript": null,
          "transcript_viewable": true,
          "spiderable": true,
          "custom_message": "",
          "custom_message_show": null,
          "custom_message_recipient_only": null,
          "show_job_insights": false,
          "certificate_design": {
              "id": 173420,
              "size": "a4",
              "orientation": "landscape",
              "background_bleeds": false,
              "attribute_keys": { },
              "kind": "certificate",
              "rasterized_content_url": "https://pdf.ms.badge.net/design/image?signed-data=%7B%22design%22%3A%22f8a2edb3-35a5-4cdb-901c-d559950248f1%22%2C%22env%22%3A%22production%22%2C%22signature%22%3A%22515619dd39b9dab19f2fd63bc80123cbbcbe75afce481ce7b58ce126c047a433%22%7D",
              "background": "https://s3.amazonaws.com/accredible-api-templates/1511931881109.png",
              "blocks": [
                  {
                      "font": "Dancing Script",
                      "font_weight": 400,
                      "font_size": "30px",
                      "top": "32.999%",
                      "left": "0.5%",
                      "image_width": "99.625%",
                      "model": "This certificate is awarded to",
                      "color": "#000000",
                      "align": "center",
                      "z_index": 1
                  },
                  {
                      "font": "Oswald",
                      "font_weight": 400,
                      "font_size": "35px",
                      "top": "41%",
                      "left": "0%",
                      "image_width": "100.000%",
                      "model": "[recipient.name]",
                      "color": "#341f67",
                      "align": "center",
                      "z_index": 2
                  },
                  {
                      "font": "Lato",
                      "font_weight": 400,
                      "font_size": "20px",
                      "top": "51.778%",
                      "left": "0.000%",
                      "image_width": "99.875%",
                      "model": "has successfully completed the course",
                      "color": "#000000",
                      "align": "center",
                      "z_index": 3
                  },
                  {
                      "font": "Lato",
                      "font_weight": 700,
                      "font_size": "50px",
                      "top": "14.777999999999999%",
                      "left": "0.000%",
                      "image_width": "99.875%",
                      "model": "CERTIFICATE",
                      "color": "#341f67",
                      "align": "center",
                      "selected": false,
                      "edit": false,
                      "z_index": 4
                  },
                  {
                      "font": "Lato",
                      "font_weight": 400,
                      "font_size": "20px",
                      "top": "26.778%",
                      "left": "0.000%",
                      "image_width": "99.875%",
                      "model": "OF ACHIEVEMENT",
                      "color": "#333f83",
                      "align": "center",
                      "z_index": 5
                  },
                  {
                      "font": "Lato",
                      "font_weight": 400,
                      "font_size": "22px",
                      "top": "57.778%",
                      "left": "0.000%",
                      "image_width": "99.875%",
                      "model": "[group.course_name]",
                      "color": "#000000",
                      "align": "center",
                      "z_index": 6
                  },
                  {
                      "top": "78.675%",
                      "left": "5.250%",
                      "model": "[credential.issued_on]",
                      "font": "Source Sans Pro",
                      "font_weight": 400,
                      "color": "#000000",
                      "font_size": "16px",
                      "image_width": "28.000%",
                      "scale_to_fit": false,
                      "selected": false,
                      "edit": false,
                      "z_index": 7
                  },
                  {
                      "top": "77.968%",
                      "left": "63.625%",
                      "model": "[credential.grade]",
                      "font": "Source Sans Pro",
                      "font_weight": 400,
                      "color": "#000000",
                      "font_size": "16px",
                      "image_width": "32.875%",
                      "scale_to_fit": false,
                      "selected": false,
                      "edit": false,
                      "z_index": 8
                  }
              ],
              "svg": null
          },
          "badge_design": null
      },
      "associated_collections": [ ]
  }

}
